[package]
name = "learning-gr"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
rand = "0.8"
winit = "0.28"
pixels = "0.12"
env_logger = "0.10"
log = "0.4"
rayon = "1.10"
noise = "0.9.0"
hecs = "0.7"
nalgebra = "0.33.2"
gltf = "1.4.1"
